version: '3.8'

services:
  drfedu:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
      - static_volume:/app/static
    ports:
      - "8000:8000"
    networks:
      - DRFEdu-network
    depends_on:
      - postgres-db
      - redis
      - celery
    env_file:
      - ./.env.docker

  postgres-db:
    image: postgres:latest
    container_name: postgres
    environment:
      POSTGRES_DB: DRFEduDB
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data
    networks:
      - DRFEdu-network

  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    networks:
      - DRFEdu-network

  celery:
    build:
      context: .
    command: celery -A DRFEdu worker --loglevel=info
    depends_on:
      - redis
      - postgres-db
    volumes:
      - .:/app
    networks:
      - DRFEdu-network
    env_file:
      - ./.env.docker

  celery-beat:
    build:
      context: .
    command: celery -A DRFEdu beat --loglevel=info
    depends_on:
      - celery
      - redis
      - postgres-db
    volumes:
      - .:/app
    networks:
      - DRFEdu-network
    env_file:
      - ./.env.docker

  nginx:
    image: nginx:latest
    volumes:
      - ./conf/nginx.conf:/etc/nginx/nginx.conf
      - static_volume:/static
    ports:
      - "80:80"
    networks:
      - DRFEdu-network
    depends_on:
      - drfedu

volumes:
  pg_data:
  static_volume:

networks:
  DRFEdu-network:
    driver: bridge